name: testing

on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/**/*'
      - 'tests/**/*'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '.github/workflows/testing.yml'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'src/**/*'
      - 'tests/**/*'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '.github/workflows/testing.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    # container:
    #   image: xd009642/tarpaulin
    #   options: --security-opt seccomp=unconfined
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: install rust cache
        uses: Swatinem/rust-cache@v2
      - name: run tests
        run: cargo test

  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: install rust cache
        uses: Swatinem/rust-cache@v2
      - name: run coverage check
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.15.0'
          args: '--workspace --fail-under 5 --exclude-files tests/*'
